#!/usr/bin/python
# coding=utf-8
import sys
import getopt
'''
novel -l
查询novel列表，返回novel名称和ID

novel -t 3 -i 1
id为1的novel最新的3章title和dtl_id

novel -c 3
列出dtl_id为3的文章内容

ps:
novel table
列出所有novel list的最新3章的title和dtl_id

novel content ?
必须指定dtl_id
'''

'''
c) 调用getopt函数。函数返回两个列表：opts和args。opts为分析出的格式信息。
args为不属于格式信息的剩余的命令行参数。opts是一个两元组的列表。
每个元素为：(选项串,附加参数)。如果没有附加参数则为空串''。

getopt函数的第三个参数[, long_options]为可选的长选项参数，上面例子中的都为短选项(如-i -o)
长选项格式举例:
--version
--file=error.txt
让一个脚本同时支持短选项和长选项
getopt.getopt(sys.argv[1:], "hi:o:", ["version", "file="])
'''

if __name__ == '__main__':
	if(len(sys.argv)<2):
		print '请输入执行参数';
		sys.exit();

	try:
		opts,args = getopt.getopt(sys.argv[1:],"lot:i:c:")
	except:
		print '参数异常';
		sys.exit();

	if(len(opts)==0):
		print '请输入执行参数';
		sys.exit();


	for op,value in opts:
		novellist = "gg"
		if op == "-l":
			print 'l';
		elif op == "-t":
			print '-t ' + value;
		elif op == "-i":
			print '-i ' + value;
		elif op == "-c":
			print '-c ' + value;

	print novellist;




